# Generated by Django 3.0.4 on 2020-07-03 09:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='a')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField()),
                ('previous_hash', models.CharField(max_length=64)),
                ('nonce', models.IntegerField()),
                ('difficulty', models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(32768), django.core.validators.MinValueValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Body')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Header')),
            ],
        ),
    ]
